# Generated by Django 4.2.15 on 2024-10-15 07:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storyline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyline.quest')),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('openai_assistant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(default='gpt-4o', max_length=255)),
                ('general_instructions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.generalinstructions')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyline.quest')),
                ('quest_instructions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.questinstructions')),
            ],
        ),
    ]
