# Generated by Django 4.2.15 on 2024-10-15 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyline', '0003_remove_quest_assistant_id'),
        ('assistants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistants.assistant')),
                ('quest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storyline.quest')),
            ],
        ),
    ]
