# Generated by Django 4.2.15 on 2024-10-15 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyline', '0002_alter_quest_assistant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='assistant_id',
        ),
    ]
