# Generated by Django 4.2.15 on 2024-10-17 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyline', '0003_remove_quest_assistant_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adventure',
            unique_together={('story', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='quest',
            unique_together={('adventure', 'title')},
        ),
        migrations.RemoveField(
            model_name='story',
            name='story_num',
        ),
        migrations.AddField(
            model_name='adventure',
            name='prev',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_node', to='storyline.adventure'),
        ),
        migrations.AddField(
            model_name='quest',
            name='prev',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_node', to='storyline.quest'),
        ),
        migrations.AddField(
            model_name='story',
            name='prev',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_node', to='storyline.story'),
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='adventure_num',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='quest_num',
        ),
    ]
