# Generated by Django 4.2.15 on 2024-10-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyline', '0004_alter_adventure_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quest',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
