# Generated by Django 4.2.15 on 2024-10-17 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyline', '0005_alter_adventure_title_alter_quest_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adventure',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='quest',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='story',
            name='prev',
        ),
        migrations.AddField(
            model_name='adventure',
            name='adventure_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adventure',
            name='next_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_nodes', to='storyline.adventure'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='prev_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_nodes', to='storyline.adventure'),
        ),
        migrations.AddField(
            model_name='quest',
            name='next_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_nodes', to='storyline.quest'),
        ),
        migrations.AddField(
            model_name='quest',
            name='prev_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_nodes', to='storyline.quest'),
        ),
        migrations.AddField(
            model_name='quest',
            name='quest_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='next_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_nodes', to='storyline.story'),
        ),
        migrations.AddField(
            model_name='story',
            name='prev_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_nodes', to='storyline.story'),
        ),
        migrations.AddField(
            model_name='story',
            name='story_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='adventure',
            unique_together={('story', 'adventure_num')},
        ),
        migrations.AlterUniqueTogether(
            name='quest',
            unique_together={('adventure', 'quest_num')},
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='prev',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='prev',
        ),
    ]
