# Generated by Django 4.2.15 on 2024-10-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyline', '0007_alter_adventure_options_alter_quest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
