# Generated by Django 4.2.15 on 2024-10-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyline', '0008_alter_story_story_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quest',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
