# Generated by Django 4.2.15 on 2024-10-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyline', '0010_remove_adventure_exclude_remove_quest_exclude_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adventure',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='quest',
            unique_together=set(),
        ),
    ]
