# Generated by Django 4.2.15 on 2024-11-11 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyline', '0011_alter_adventure_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='objectives',
        ),
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='storyline.quest')),
            ],
        ),
    ]
