name: Django CI
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
jobs:
  test:
    runs-on: ubuntu-latest
    environment: development
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}
      DEFAULT_API_VERSION: ${{ secrets.DEFAULT_API_VERSION }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/development.txt
      - name: Run migrations
        run: python manage.py migrate
      - name: Run tests with pytest
        run: pytest
